# Metadata
title: Ben Davies
author: Ben Davies
email: ben.davies@motu.org.nz
github-url:  https://github.com/bldavies
google-analytics: UA-123726505-1
linkedin-url: https://www.linkedin.com/in/bl-davies/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
include:
  - _pages
