# Metadata
title: Ben Davies
author: Ben Davies
email: ben.davies@motu.org.nz
github-url:  https://github.com/bldavies
linkedin-url: https://www.linkedin.com/in/nzbendavies/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
include:
  - _pages
